// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTyCGzfl0f-3mHQG4OWvtw3EcEN0qlXMI',
    appId: '1:446994133291:web:4edf1a32d75f1f1fae956e',
    messagingSenderId: '446994133291',
    projectId: 'salon-web-e7012',
    authDomain: 'salon-web-e7012.firebaseapp.com',
    storageBucket: 'salon-web-e7012.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_eH8Cy6F5bfivtCsGnB7LElPByW_ek08',
    appId: '1:446994133291:android:f2e84c9bd2316607ae956e',
    messagingSenderId: '446994133291',
    projectId: 'salon-web-e7012',
    storageBucket: 'salon-web-e7012.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpI5Daos4TQiG65uzI2PJibord-iyajG0',
    appId: '1:446994133291:ios:589ca4fb7f7d9cf7ae956e',
    messagingSenderId: '446994133291',
    projectId: 'salon-web-e7012',
    storageBucket: 'salon-web-e7012.appspot.com',
    iosBundleId: 'com.example.salonConfigWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpI5Daos4TQiG65uzI2PJibord-iyajG0',
    appId: '1:446994133291:ios:9f628102008a8e59ae956e',
    messagingSenderId: '446994133291',
    projectId: 'salon-web-e7012',
    storageBucket: 'salon-web-e7012.appspot.com',
    iosBundleId: 'com.example.salonConfigWeb.RunnerTests',
  );
}
